/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IPendleRouter } from "../IPendleRouter";

export class IPendleRouter__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPendleRouter {
    return new Contract(address, _abi, signerOrProvider) as IPendleRouter;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "token0Amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "token1Amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "market",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "exactInLp",
        type: "uint256",
      },
    ],
    name: "Exit",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "token0Amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "token1Amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "market",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "exactOutLp",
        type: "uint256",
      },
    ],
    name: "Join",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "marketFactoryId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "xyt",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "market",
        type: "address",
      },
    ],
    name: "MarketCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "trader",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "inToken",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "outToken",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "exactIn",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "exactOut",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "market",
        type: "address",
      },
    ],
    name: "SwapEvent",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_marketFactoryId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "_xyt",
        type: "address",
      },
      {
        internalType: "address",
        name: "_token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_desiredXytAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_desiredTokenAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_xytMinAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_tokenMinAmount",
        type: "uint256",
      },
    ],
    name: "addMarketLiquidityDual",
    outputs: [
      {
        internalType: "uint256",
        name: "amountXytUsed",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amountTokenUsed",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "lpOut",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "marketFactoryId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "xyt",
        type: "address",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "bool",
        name: "forXyt",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "exactInAsset",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minOutLp",
        type: "uint256",
      },
    ],
    name: "addMarketLiquiditySingle",
    outputs: [
      {
        internalType: "uint256",
        name: "exactOutLp",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "marketFactoryId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "xyt",
        type: "address",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "initialXytLiquidity",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "initialTokenLiquidity",
        type: "uint256",
      },
    ],
    name: "bootstrapMarket",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "marketFactoryId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "xyt",
        type: "address",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "createMarket",
    outputs: [
      {
        internalType: "address",
        name: "market",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "data",
    outputs: [
      {
        internalType: "contract IPendleData",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "forgeId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "underlyingAsset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "expiry",
        type: "uint256",
      },
    ],
    name: "newYieldContracts",
    outputs: [
      {
        internalType: "address",
        name: "ot",
        type: "address",
      },
      {
        internalType: "address",
        name: "xyt",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "forgeId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "underlyingAsset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "expiry",
        type: "uint256",
      },
    ],
    name: "redeemAfterExpiry",
    outputs: [
      {
        internalType: "uint256",
        name: "redeemedAmount",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "forgeId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "underlyingAsset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "expiry",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "redeemDueInterests",
    outputs: [
      {
        internalType: "uint256",
        name: "interests",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "market",
        type: "address",
      },
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "redeemLpInterests",
    outputs: [
      {
        internalType: "uint256",
        name: "interests",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "forgeId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "underlyingAsset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "expiry",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amountToRedeem",
        type: "uint256",
      },
    ],
    name: "redeemUnderlying",
    outputs: [
      {
        internalType: "uint256",
        name: "redeemedAmount",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "marketFactoryId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "xyt",
        type: "address",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "exactInLp",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minOutXyt",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minOutToken",
        type: "uint256",
      },
    ],
    name: "removeMarketLiquidityDual",
    outputs: [
      {
        internalType: "uint256",
        name: "exactOutXyt",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "exactOutToken",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "marketFactoryId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "xyt",
        type: "address",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "bool",
        name: "forXyt",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "exactInLp",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minOutAsset",
        type: "uint256",
      },
    ],
    name: "removeMarketLiquiditySingle",
    outputs: [
      {
        internalType: "uint256",
        name: "exactOutXyt",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "exactOutToken",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "forgeId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "oldExpiry",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "underlyingAsset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "newExpiry",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "renewalRate",
        type: "uint256",
      },
    ],
    name: "renewYield",
    outputs: [
      {
        internalType: "uint256",
        name: "redeemedAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amountRenewed",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "ot",
        type: "address",
      },
      {
        internalType: "address",
        name: "xyt",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amountTokenMinted",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenIn",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenOut",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "inTotalAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minOutTotalAmount",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "marketFactoryId",
        type: "bytes32",
      },
    ],
    name: "swapExactIn",
    outputs: [
      {
        internalType: "uint256",
        name: "outTotalAmount",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenIn",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenOut",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "outTotalAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maxInTotalAmount",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "marketFactoryId",
        type: "bytes32",
      },
    ],
    name: "swapExactOut",
    outputs: [
      {
        internalType: "uint256",
        name: "inTotalAmount",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "forgeId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "underlyingAsset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "expiry",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amountToTokenize",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "tokenizeYield",
    outputs: [
      {
        internalType: "address",
        name: "ot",
        type: "address",
      },
      {
        internalType: "address",
        name: "xyt",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amountTokenMinted",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "weth",
    outputs: [
      {
        internalType: "contract IWETH",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
