/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IPermissionsV2 } from "../IPermissionsV2";

export class IPermissionsV2__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPermissionsV2 {
    return new Contract(address, _abi, signerOrProvider) as IPermissionsV2;
  }
}

const _abi = [
  {
    inputs: [],
    name: "governanceManager",
    outputs: [
      {
        internalType: "contract PendleGovernanceManager",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];
