/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";

import type { PendleGovernanceManager } from "../PendleGovernanceManager";

export class PendleGovernanceManager__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    _governance: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<PendleGovernanceManager> {
    return super.deploy(
      _governance,
      overrides || {}
    ) as Promise<PendleGovernanceManager>;
  }
  getDeployTransaction(
    _governance: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_governance, overrides || {});
  }
  attach(address: string): PendleGovernanceManager {
    return super.attach(address) as PendleGovernanceManager;
  }
  connect(signer: Signer): PendleGovernanceManager__factory {
    return super.connect(signer) as PendleGovernanceManager__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PendleGovernanceManager {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as PendleGovernanceManager;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_governance",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "newGovernance",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "previousGovernance",
        type: "address",
      },
    ],
    name: "GovernanceClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "pendingGovernance",
        type: "address",
      },
    ],
    name: "TransferGovernancePending",
    type: "event",
  },
  {
    inputs: [],
    name: "claimGovernance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "governance",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pendingGovernance",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_governance",
        type: "address",
      },
    ],
    name: "transferGovernance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060405161036a38038061036a8339818101604052602081101561003357600080fd5b50516001600160a01b03811661007f576040805162461bcd60e51b815260206004820152600c60248201526b5a45524f5f4144445245535360a01b604482015290519081900360640190fd5b600080546001600160a01b039092166001600160a01b03199092169190911790556102bb806100af6000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c80635aa6e675146100515780635d36b19014610075578063d38bfff41461007f578063f39c38a0146100a5575b600080fd5b6100596100ad565b604080516001600160a01b039092168252519081900360200190f35b61007d6100bc565b005b61007d6004803603602081101561009557600080fd5b50356001600160a01b0316610181565b610059610276565b6000546001600160a01b031681565b6001546001600160a01b0316331461010e576040805162461bcd60e51b815260206004820152601060248201526f57524f4e475f474f5645524e414e434560801b604482015290519081900360640190fd5b600154600054604080516001600160a01b03938416815292909116602083015280517fb0758afd6736a6cb3153d002696dcdd7615f1ff7c626469b3daf3358286c1c249281900390910190a160018054600080546001600160a01b03199081166001600160a01b03841617909155169055565b6000546001600160a01b031633146101d2576040805162461bcd60e51b815260206004820152600f60248201526e4f4e4c595f474f5645524e414e434560881b604482015290519081900360640190fd5b6001600160a01b03811661021c576040805162461bcd60e51b815260206004820152600c60248201526b5a45524f5f4144445245535360a01b604482015290519081900360640190fd5b600180546001600160a01b0319166001600160a01b03838116919091179182905560408051929091168252517f70f2dff90d8145da945114cc37c5ffde0eef9306ad5efbd39cae52dc28f9cbf3916020908290030190a150565b6001546001600160a01b03168156fea26469706673582212203fd95f4059fb52d7afa57f5508ece9c8b74ae587d0b489f774c5bd4083b344f064736f6c63430007060033";
