/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IPendleGenericForgeInterface extends ethers.utils.Interface {
  functions: {
    "data()": FunctionFragment;
    "dueInterests(address,uint256,address)": FunctionFragment;
    "forgeId()": FunctionFragment;
    "getExchangeRate(address)": FunctionFragment;
    "getYieldBearingToken(address)": FunctionFragment;
    "mintOtAndXyt(address,uint256,uint256,address)": FunctionFragment;
    "newYieldContracts(address,uint256)": FunctionFragment;
    "redeemAfterExpiry(address,address,uint256)": FunctionFragment;
    "redeemDueInterests(address,address,uint256)": FunctionFragment;
    "redeemUnderlying(address,address,uint256,uint256)": FunctionFragment;
    "rewardManager()": FunctionFragment;
    "rewardToken()": FunctionFragment;
    "router()": FunctionFragment;
    "setUpEmergencyMode(address,uint256,address)": FunctionFragment;
    "updateDueInterests(address,uint256,address)": FunctionFragment;
    "updatePendingRewards(address,uint256,address)": FunctionFragment;
    "withdrawForgeFee(address,uint256)": FunctionFragment;
    "yieldContractDeployer()": FunctionFragment;
    "yieldTokenHolders(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "data", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "dueInterests",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "forgeId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getExchangeRate",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getYieldBearingToken",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "mintOtAndXyt",
    values: [string, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "newYieldContracts",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "redeemAfterExpiry",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "redeemDueInterests",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "redeemUnderlying",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rewardManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardToken",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "router", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setUpEmergencyMode",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateDueInterests",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePendingRewards",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawForgeFee",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "yieldContractDeployer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "yieldTokenHolders",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "data", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "dueInterests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "forgeId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getExchangeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getYieldBearingToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintOtAndXyt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "newYieldContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redeemAfterExpiry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redeemDueInterests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redeemUnderlying",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "router", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setUpEmergencyMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateDueInterests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePendingRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawForgeFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "yieldContractDeployer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "yieldTokenHolders",
    data: BytesLike
  ): Result;

  events: {
    "DueInterestsSettled(bytes32,address,uint256,uint256,uint256,address)": EventFragment;
    "ForgeFeeWithdrawn(bytes32,address,uint256,uint256)": EventFragment;
    "MintYieldTokens(bytes32,address,uint256,uint256,uint256,address)": EventFragment;
    "NewYieldContracts(bytes32,address,uint256,address,address,address)": EventFragment;
    "RedeemYieldToken(bytes32,address,uint256,uint256,uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DueInterestsSettled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ForgeFeeWithdrawn"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MintYieldTokens"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewYieldContracts"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RedeemYieldToken"): EventFragment;
}

export class IPendleGenericForge extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IPendleGenericForgeInterface;

  functions: {
    data(overrides?: CallOverrides): Promise<[string]>;

    "data()"(overrides?: CallOverrides): Promise<[string]>;

    dueInterests(
      _underlyingAsset: string,
      expiry: BigNumberish,
      _user: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "dueInterests(address,uint256,address)"(
      _underlyingAsset: string,
      expiry: BigNumberish,
      _user: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    forgeId(overrides?: CallOverrides): Promise<[string]>;

    "forgeId()"(overrides?: CallOverrides): Promise<[string]>;

    getExchangeRate(
      _underlyingAsset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "getExchangeRate(address)"(
      _underlyingAsset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getYieldBearingToken(
      underlyingAsset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "getYieldBearingToken(address)"(
      underlyingAsset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    mintOtAndXyt(
      underlyingAsset: string,
      expiry: BigNumberish,
      amountToTokenize: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "mintOtAndXyt(address,uint256,uint256,address)"(
      underlyingAsset: string,
      expiry: BigNumberish,
      amountToTokenize: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    newYieldContracts(
      underlyingAsset: string,
      expiry: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "newYieldContracts(address,uint256)"(
      underlyingAsset: string,
      expiry: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    redeemAfterExpiry(
      user: string,
      underlyingAsset: string,
      expiry: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "redeemAfterExpiry(address,address,uint256)"(
      user: string,
      underlyingAsset: string,
      expiry: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    redeemDueInterests(
      user: string,
      underlyingAsset: string,
      expiry: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "redeemDueInterests(address,address,uint256)"(
      user: string,
      underlyingAsset: string,
      expiry: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    redeemUnderlying(
      user: string,
      underlyingAsset: string,
      expiry: BigNumberish,
      amountToRedeem: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "redeemUnderlying(address,address,uint256,uint256)"(
      user: string,
      underlyingAsset: string,
      expiry: BigNumberish,
      amountToRedeem: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    rewardManager(overrides?: CallOverrides): Promise<[string]>;

    "rewardManager()"(overrides?: CallOverrides): Promise<[string]>;

    rewardToken(overrides?: CallOverrides): Promise<[string]>;

    "rewardToken()"(overrides?: CallOverrides): Promise<[string]>;

    router(overrides?: CallOverrides): Promise<[string]>;

    "router()"(overrides?: CallOverrides): Promise<[string]>;

    setUpEmergencyMode(
      _underlyingAsset: string,
      _expiry: BigNumberish,
      spender: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setUpEmergencyMode(address,uint256,address)"(
      _underlyingAsset: string,
      _expiry: BigNumberish,
      spender: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateDueInterests(
      underlyingAsset: string,
      expiry: BigNumberish,
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "updateDueInterests(address,uint256,address)"(
      underlyingAsset: string,
      expiry: BigNumberish,
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updatePendingRewards(
      _underlyingAsset: string,
      _expiry: BigNumberish,
      _user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "updatePendingRewards(address,uint256,address)"(
      _underlyingAsset: string,
      _expiry: BigNumberish,
      _user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawForgeFee(
      underlyingAsset: string,
      expiry: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "withdrawForgeFee(address,uint256)"(
      underlyingAsset: string,
      expiry: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    yieldContractDeployer(overrides?: CallOverrides): Promise<[string]>;

    "yieldContractDeployer()"(overrides?: CallOverrides): Promise<[string]>;

    yieldTokenHolders(
      _underlyingAsset: string,
      _expiry: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { yieldTokenHolder: string }>;

    "yieldTokenHolders(address,uint256)"(
      _underlyingAsset: string,
      _expiry: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { yieldTokenHolder: string }>;
  };

  data(overrides?: CallOverrides): Promise<string>;

  "data()"(overrides?: CallOverrides): Promise<string>;

  dueInterests(
    _underlyingAsset: string,
    expiry: BigNumberish,
    _user: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "dueInterests(address,uint256,address)"(
    _underlyingAsset: string,
    expiry: BigNumberish,
    _user: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  forgeId(overrides?: CallOverrides): Promise<string>;

  "forgeId()"(overrides?: CallOverrides): Promise<string>;

  getExchangeRate(
    _underlyingAsset: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "getExchangeRate(address)"(
    _underlyingAsset: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getYieldBearingToken(
    underlyingAsset: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "getYieldBearingToken(address)"(
    underlyingAsset: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  mintOtAndXyt(
    underlyingAsset: string,
    expiry: BigNumberish,
    amountToTokenize: BigNumberish,
    to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "mintOtAndXyt(address,uint256,uint256,address)"(
    underlyingAsset: string,
    expiry: BigNumberish,
    amountToTokenize: BigNumberish,
    to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  newYieldContracts(
    underlyingAsset: string,
    expiry: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "newYieldContracts(address,uint256)"(
    underlyingAsset: string,
    expiry: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  redeemAfterExpiry(
    user: string,
    underlyingAsset: string,
    expiry: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "redeemAfterExpiry(address,address,uint256)"(
    user: string,
    underlyingAsset: string,
    expiry: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  redeemDueInterests(
    user: string,
    underlyingAsset: string,
    expiry: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "redeemDueInterests(address,address,uint256)"(
    user: string,
    underlyingAsset: string,
    expiry: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  redeemUnderlying(
    user: string,
    underlyingAsset: string,
    expiry: BigNumberish,
    amountToRedeem: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "redeemUnderlying(address,address,uint256,uint256)"(
    user: string,
    underlyingAsset: string,
    expiry: BigNumberish,
    amountToRedeem: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  rewardManager(overrides?: CallOverrides): Promise<string>;

  "rewardManager()"(overrides?: CallOverrides): Promise<string>;

  rewardToken(overrides?: CallOverrides): Promise<string>;

  "rewardToken()"(overrides?: CallOverrides): Promise<string>;

  router(overrides?: CallOverrides): Promise<string>;

  "router()"(overrides?: CallOverrides): Promise<string>;

  setUpEmergencyMode(
    _underlyingAsset: string,
    _expiry: BigNumberish,
    spender: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setUpEmergencyMode(address,uint256,address)"(
    _underlyingAsset: string,
    _expiry: BigNumberish,
    spender: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateDueInterests(
    underlyingAsset: string,
    expiry: BigNumberish,
    user: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "updateDueInterests(address,uint256,address)"(
    underlyingAsset: string,
    expiry: BigNumberish,
    user: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updatePendingRewards(
    _underlyingAsset: string,
    _expiry: BigNumberish,
    _user: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "updatePendingRewards(address,uint256,address)"(
    _underlyingAsset: string,
    _expiry: BigNumberish,
    _user: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawForgeFee(
    underlyingAsset: string,
    expiry: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "withdrawForgeFee(address,uint256)"(
    underlyingAsset: string,
    expiry: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  yieldContractDeployer(overrides?: CallOverrides): Promise<string>;

  "yieldContractDeployer()"(overrides?: CallOverrides): Promise<string>;

  yieldTokenHolders(
    _underlyingAsset: string,
    _expiry: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "yieldTokenHolders(address,uint256)"(
    _underlyingAsset: string,
    _expiry: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    data(overrides?: CallOverrides): Promise<string>;

    "data()"(overrides?: CallOverrides): Promise<string>;

    dueInterests(
      _underlyingAsset: string,
      expiry: BigNumberish,
      _user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "dueInterests(address,uint256,address)"(
      _underlyingAsset: string,
      expiry: BigNumberish,
      _user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    forgeId(overrides?: CallOverrides): Promise<string>;

    "forgeId()"(overrides?: CallOverrides): Promise<string>;

    getExchangeRate(
      _underlyingAsset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getExchangeRate(address)"(
      _underlyingAsset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getYieldBearingToken(
      underlyingAsset: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "getYieldBearingToken(address)"(
      underlyingAsset: string,
      overrides?: CallOverrides
    ): Promise<string>;

    mintOtAndXyt(
      underlyingAsset: string,
      expiry: BigNumberish,
      amountToTokenize: BigNumberish,
      to: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber] & {
        ot: string;
        xyt: string;
        amountTokenMinted: BigNumber;
      }
    >;

    "mintOtAndXyt(address,uint256,uint256,address)"(
      underlyingAsset: string,
      expiry: BigNumberish,
      amountToTokenize: BigNumberish,
      to: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber] & {
        ot: string;
        xyt: string;
        amountTokenMinted: BigNumber;
      }
    >;

    newYieldContracts(
      underlyingAsset: string,
      expiry: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, string] & { ot: string; xyt: string }>;

    "newYieldContracts(address,uint256)"(
      underlyingAsset: string,
      expiry: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, string] & { ot: string; xyt: string }>;

    redeemAfterExpiry(
      user: string,
      underlyingAsset: string,
      expiry: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "redeemAfterExpiry(address,address,uint256)"(
      user: string,
      underlyingAsset: string,
      expiry: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    redeemDueInterests(
      user: string,
      underlyingAsset: string,
      expiry: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "redeemDueInterests(address,address,uint256)"(
      user: string,
      underlyingAsset: string,
      expiry: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    redeemUnderlying(
      user: string,
      underlyingAsset: string,
      expiry: BigNumberish,
      amountToRedeem: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "redeemUnderlying(address,address,uint256,uint256)"(
      user: string,
      underlyingAsset: string,
      expiry: BigNumberish,
      amountToRedeem: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rewardManager(overrides?: CallOverrides): Promise<string>;

    "rewardManager()"(overrides?: CallOverrides): Promise<string>;

    rewardToken(overrides?: CallOverrides): Promise<string>;

    "rewardToken()"(overrides?: CallOverrides): Promise<string>;

    router(overrides?: CallOverrides): Promise<string>;

    "router()"(overrides?: CallOverrides): Promise<string>;

    setUpEmergencyMode(
      _underlyingAsset: string,
      _expiry: BigNumberish,
      spender: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setUpEmergencyMode(address,uint256,address)"(
      _underlyingAsset: string,
      _expiry: BigNumberish,
      spender: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateDueInterests(
      underlyingAsset: string,
      expiry: BigNumberish,
      user: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "updateDueInterests(address,uint256,address)"(
      underlyingAsset: string,
      expiry: BigNumberish,
      user: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updatePendingRewards(
      _underlyingAsset: string,
      _expiry: BigNumberish,
      _user: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "updatePendingRewards(address,uint256,address)"(
      _underlyingAsset: string,
      _expiry: BigNumberish,
      _user: string,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawForgeFee(
      underlyingAsset: string,
      expiry: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "withdrawForgeFee(address,uint256)"(
      underlyingAsset: string,
      expiry: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    yieldContractDeployer(overrides?: CallOverrides): Promise<string>;

    "yieldContractDeployer()"(overrides?: CallOverrides): Promise<string>;

    yieldTokenHolders(
      _underlyingAsset: string,
      _expiry: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "yieldTokenHolders(address,uint256)"(
      _underlyingAsset: string,
      _expiry: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    DueInterestsSettled(
      forgeId: null,
      underlyingAsset: string | null,
      expiry: BigNumberish | null,
      amount: null,
      forgeFeeAmount: null,
      user: string | null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber, BigNumber, string],
      {
        forgeId: string;
        underlyingAsset: string;
        expiry: BigNumber;
        amount: BigNumber;
        forgeFeeAmount: BigNumber;
        user: string;
      }
    >;

    ForgeFeeWithdrawn(
      forgeId: null,
      underlyingAsset: string | null,
      expiry: BigNumberish | null,
      amount: null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber],
      {
        forgeId: string;
        underlyingAsset: string;
        expiry: BigNumber;
        amount: BigNumber;
      }
    >;

    MintYieldTokens(
      forgeId: null,
      underlyingAsset: string | null,
      expiry: BigNumberish | null,
      amountToTokenize: null,
      amountTokenMinted: null,
      user: string | null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber, BigNumber, string],
      {
        forgeId: string;
        underlyingAsset: string;
        expiry: BigNumber;
        amountToTokenize: BigNumber;
        amountTokenMinted: BigNumber;
        user: string;
      }
    >;

    NewYieldContracts(
      forgeId: null,
      underlyingAsset: string | null,
      expiry: BigNumberish | null,
      ot: null,
      xyt: null,
      yieldBearingAsset: null
    ): TypedEventFilter<
      [string, string, BigNumber, string, string, string],
      {
        forgeId: string;
        underlyingAsset: string;
        expiry: BigNumber;
        ot: string;
        xyt: string;
        yieldBearingAsset: string;
      }
    >;

    RedeemYieldToken(
      forgeId: null,
      underlyingAsset: string | null,
      expiry: BigNumberish | null,
      amountToRedeem: null,
      redeemedAmount: null,
      user: string | null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber, BigNumber, string],
      {
        forgeId: string;
        underlyingAsset: string;
        expiry: BigNumber;
        amountToRedeem: BigNumber;
        redeemedAmount: BigNumber;
        user: string;
      }
    >;
  };

  estimateGas: {
    data(overrides?: CallOverrides): Promise<BigNumber>;

    "data()"(overrides?: CallOverrides): Promise<BigNumber>;

    dueInterests(
      _underlyingAsset: string,
      expiry: BigNumberish,
      _user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "dueInterests(address,uint256,address)"(
      _underlyingAsset: string,
      expiry: BigNumberish,
      _user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    forgeId(overrides?: CallOverrides): Promise<BigNumber>;

    "forgeId()"(overrides?: CallOverrides): Promise<BigNumber>;

    getExchangeRate(
      _underlyingAsset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "getExchangeRate(address)"(
      _underlyingAsset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getYieldBearingToken(
      underlyingAsset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "getYieldBearingToken(address)"(
      underlyingAsset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    mintOtAndXyt(
      underlyingAsset: string,
      expiry: BigNumberish,
      amountToTokenize: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "mintOtAndXyt(address,uint256,uint256,address)"(
      underlyingAsset: string,
      expiry: BigNumberish,
      amountToTokenize: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    newYieldContracts(
      underlyingAsset: string,
      expiry: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "newYieldContracts(address,uint256)"(
      underlyingAsset: string,
      expiry: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    redeemAfterExpiry(
      user: string,
      underlyingAsset: string,
      expiry: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "redeemAfterExpiry(address,address,uint256)"(
      user: string,
      underlyingAsset: string,
      expiry: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    redeemDueInterests(
      user: string,
      underlyingAsset: string,
      expiry: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "redeemDueInterests(address,address,uint256)"(
      user: string,
      underlyingAsset: string,
      expiry: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    redeemUnderlying(
      user: string,
      underlyingAsset: string,
      expiry: BigNumberish,
      amountToRedeem: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "redeemUnderlying(address,address,uint256,uint256)"(
      user: string,
      underlyingAsset: string,
      expiry: BigNumberish,
      amountToRedeem: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    rewardManager(overrides?: CallOverrides): Promise<BigNumber>;

    "rewardManager()"(overrides?: CallOverrides): Promise<BigNumber>;

    rewardToken(overrides?: CallOverrides): Promise<BigNumber>;

    "rewardToken()"(overrides?: CallOverrides): Promise<BigNumber>;

    router(overrides?: CallOverrides): Promise<BigNumber>;

    "router()"(overrides?: CallOverrides): Promise<BigNumber>;

    setUpEmergencyMode(
      _underlyingAsset: string,
      _expiry: BigNumberish,
      spender: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setUpEmergencyMode(address,uint256,address)"(
      _underlyingAsset: string,
      _expiry: BigNumberish,
      spender: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateDueInterests(
      underlyingAsset: string,
      expiry: BigNumberish,
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "updateDueInterests(address,uint256,address)"(
      underlyingAsset: string,
      expiry: BigNumberish,
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updatePendingRewards(
      _underlyingAsset: string,
      _expiry: BigNumberish,
      _user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "updatePendingRewards(address,uint256,address)"(
      _underlyingAsset: string,
      _expiry: BigNumberish,
      _user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawForgeFee(
      underlyingAsset: string,
      expiry: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "withdrawForgeFee(address,uint256)"(
      underlyingAsset: string,
      expiry: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    yieldContractDeployer(overrides?: CallOverrides): Promise<BigNumber>;

    "yieldContractDeployer()"(overrides?: CallOverrides): Promise<BigNumber>;

    yieldTokenHolders(
      _underlyingAsset: string,
      _expiry: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "yieldTokenHolders(address,uint256)"(
      _underlyingAsset: string,
      _expiry: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    data(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "data()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    dueInterests(
      _underlyingAsset: string,
      expiry: BigNumberish,
      _user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "dueInterests(address,uint256,address)"(
      _underlyingAsset: string,
      expiry: BigNumberish,
      _user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    forgeId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "forgeId()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getExchangeRate(
      _underlyingAsset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "getExchangeRate(address)"(
      _underlyingAsset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getYieldBearingToken(
      underlyingAsset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "getYieldBearingToken(address)"(
      underlyingAsset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    mintOtAndXyt(
      underlyingAsset: string,
      expiry: BigNumberish,
      amountToTokenize: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "mintOtAndXyt(address,uint256,uint256,address)"(
      underlyingAsset: string,
      expiry: BigNumberish,
      amountToTokenize: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    newYieldContracts(
      underlyingAsset: string,
      expiry: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "newYieldContracts(address,uint256)"(
      underlyingAsset: string,
      expiry: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    redeemAfterExpiry(
      user: string,
      underlyingAsset: string,
      expiry: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "redeemAfterExpiry(address,address,uint256)"(
      user: string,
      underlyingAsset: string,
      expiry: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    redeemDueInterests(
      user: string,
      underlyingAsset: string,
      expiry: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "redeemDueInterests(address,address,uint256)"(
      user: string,
      underlyingAsset: string,
      expiry: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    redeemUnderlying(
      user: string,
      underlyingAsset: string,
      expiry: BigNumberish,
      amountToRedeem: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "redeemUnderlying(address,address,uint256,uint256)"(
      user: string,
      underlyingAsset: string,
      expiry: BigNumberish,
      amountToRedeem: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    rewardManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "rewardManager()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    rewardToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "rewardToken()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    router(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "router()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setUpEmergencyMode(
      _underlyingAsset: string,
      _expiry: BigNumberish,
      spender: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setUpEmergencyMode(address,uint256,address)"(
      _underlyingAsset: string,
      _expiry: BigNumberish,
      spender: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateDueInterests(
      underlyingAsset: string,
      expiry: BigNumberish,
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "updateDueInterests(address,uint256,address)"(
      underlyingAsset: string,
      expiry: BigNumberish,
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updatePendingRewards(
      _underlyingAsset: string,
      _expiry: BigNumberish,
      _user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "updatePendingRewards(address,uint256,address)"(
      _underlyingAsset: string,
      _expiry: BigNumberish,
      _user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawForgeFee(
      underlyingAsset: string,
      expiry: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "withdrawForgeFee(address,uint256)"(
      underlyingAsset: string,
      expiry: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    yieldContractDeployer(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "yieldContractDeployer()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    yieldTokenHolders(
      _underlyingAsset: string,
      _expiry: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "yieldTokenHolders(address,uint256)"(
      _underlyingAsset: string,
      _expiry: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
