/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface MockMarketMathInterface extends ethers.utils.Interface {
  functions: {
    "calcExactIn(tuple,tuple,uint256,uint256)": FunctionFragment;
    "calcExactOut(tuple,tuple,uint256,uint256)": FunctionFragment;
    "calcOutAmountLp(uint256,tuple,uint256,uint256)": FunctionFragment;
    "calcOutAmountToken(tuple,uint256,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "calcExactIn",
    values: [
      { weight: BigNumberish; balance: BigNumberish },
      { weight: BigNumberish; balance: BigNumberish },
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "calcExactOut",
    values: [
      { weight: BigNumberish; balance: BigNumberish },
      { weight: BigNumberish; balance: BigNumberish },
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "calcOutAmountLp",
    values: [
      BigNumberish,
      { weight: BigNumberish; balance: BigNumberish },
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "calcOutAmountToken",
    values: [
      { weight: BigNumberish; balance: BigNumberish },
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "calcExactIn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calcExactOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calcOutAmountLp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calcOutAmountToken",
    data: BytesLike
  ): Result;

  events: {};
}

export class MockMarketMath extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: MockMarketMathInterface;

  functions: {
    calcExactIn(
      inTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      outTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      exactOut: BigNumberish,
      swapFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "calcExactIn((uint256,uint256),(uint256,uint256),uint256,uint256)"(
      inTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      outTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      exactOut: BigNumberish,
      swapFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    calcExactOut(
      inTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      outTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      exactIn: BigNumberish,
      swapFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "calcExactOut((uint256,uint256),(uint256,uint256),uint256,uint256)"(
      inTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      outTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      exactIn: BigNumberish,
      swapFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    calcOutAmountLp(
      inAmount: BigNumberish,
      inTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      swapFee: BigNumberish,
      totalSupplyLp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "calcOutAmountLp(uint256,(uint256,uint256),uint256,uint256)"(
      inAmount: BigNumberish,
      inTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      swapFee: BigNumberish,
      totalSupplyLp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    calcOutAmountToken(
      outTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      totalSupplyLp: BigNumberish,
      inLp: BigNumberish,
      swapFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "calcOutAmountToken((uint256,uint256),uint256,uint256,uint256)"(
      outTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      totalSupplyLp: BigNumberish,
      inLp: BigNumberish,
      swapFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  calcExactIn(
    inTokenReserve: { weight: BigNumberish; balance: BigNumberish },
    outTokenReserve: { weight: BigNumberish; balance: BigNumberish },
    exactOut: BigNumberish,
    swapFee: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "calcExactIn((uint256,uint256),(uint256,uint256),uint256,uint256)"(
    inTokenReserve: { weight: BigNumberish; balance: BigNumberish },
    outTokenReserve: { weight: BigNumberish; balance: BigNumberish },
    exactOut: BigNumberish,
    swapFee: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  calcExactOut(
    inTokenReserve: { weight: BigNumberish; balance: BigNumberish },
    outTokenReserve: { weight: BigNumberish; balance: BigNumberish },
    exactIn: BigNumberish,
    swapFee: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "calcExactOut((uint256,uint256),(uint256,uint256),uint256,uint256)"(
    inTokenReserve: { weight: BigNumberish; balance: BigNumberish },
    outTokenReserve: { weight: BigNumberish; balance: BigNumberish },
    exactIn: BigNumberish,
    swapFee: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  calcOutAmountLp(
    inAmount: BigNumberish,
    inTokenReserve: { weight: BigNumberish; balance: BigNumberish },
    swapFee: BigNumberish,
    totalSupplyLp: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "calcOutAmountLp(uint256,(uint256,uint256),uint256,uint256)"(
    inAmount: BigNumberish,
    inTokenReserve: { weight: BigNumberish; balance: BigNumberish },
    swapFee: BigNumberish,
    totalSupplyLp: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  calcOutAmountToken(
    outTokenReserve: { weight: BigNumberish; balance: BigNumberish },
    totalSupplyLp: BigNumberish,
    inLp: BigNumberish,
    swapFee: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "calcOutAmountToken((uint256,uint256),uint256,uint256,uint256)"(
    outTokenReserve: { weight: BigNumberish; balance: BigNumberish },
    totalSupplyLp: BigNumberish,
    inLp: BigNumberish,
    swapFee: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    calcExactIn(
      inTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      outTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      exactOut: BigNumberish,
      swapFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "calcExactIn((uint256,uint256),(uint256,uint256),uint256,uint256)"(
      inTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      outTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      exactOut: BigNumberish,
      swapFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calcExactOut(
      inTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      outTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      exactIn: BigNumberish,
      swapFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "calcExactOut((uint256,uint256),(uint256,uint256),uint256,uint256)"(
      inTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      outTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      exactIn: BigNumberish,
      swapFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calcOutAmountLp(
      inAmount: BigNumberish,
      inTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      swapFee: BigNumberish,
      totalSupplyLp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "calcOutAmountLp(uint256,(uint256,uint256),uint256,uint256)"(
      inAmount: BigNumberish,
      inTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      swapFee: BigNumberish,
      totalSupplyLp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calcOutAmountToken(
      outTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      totalSupplyLp: BigNumberish,
      inLp: BigNumberish,
      swapFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "calcOutAmountToken((uint256,uint256),uint256,uint256,uint256)"(
      outTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      totalSupplyLp: BigNumberish,
      inLp: BigNumberish,
      swapFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    calcExactIn(
      inTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      outTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      exactOut: BigNumberish,
      swapFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "calcExactIn((uint256,uint256),(uint256,uint256),uint256,uint256)"(
      inTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      outTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      exactOut: BigNumberish,
      swapFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calcExactOut(
      inTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      outTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      exactIn: BigNumberish,
      swapFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "calcExactOut((uint256,uint256),(uint256,uint256),uint256,uint256)"(
      inTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      outTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      exactIn: BigNumberish,
      swapFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calcOutAmountLp(
      inAmount: BigNumberish,
      inTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      swapFee: BigNumberish,
      totalSupplyLp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "calcOutAmountLp(uint256,(uint256,uint256),uint256,uint256)"(
      inAmount: BigNumberish,
      inTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      swapFee: BigNumberish,
      totalSupplyLp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calcOutAmountToken(
      outTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      totalSupplyLp: BigNumberish,
      inLp: BigNumberish,
      swapFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "calcOutAmountToken((uint256,uint256),uint256,uint256,uint256)"(
      outTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      totalSupplyLp: BigNumberish,
      inLp: BigNumberish,
      swapFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    calcExactIn(
      inTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      outTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      exactOut: BigNumberish,
      swapFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "calcExactIn((uint256,uint256),(uint256,uint256),uint256,uint256)"(
      inTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      outTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      exactOut: BigNumberish,
      swapFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calcExactOut(
      inTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      outTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      exactIn: BigNumberish,
      swapFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "calcExactOut((uint256,uint256),(uint256,uint256),uint256,uint256)"(
      inTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      outTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      exactIn: BigNumberish,
      swapFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calcOutAmountLp(
      inAmount: BigNumberish,
      inTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      swapFee: BigNumberish,
      totalSupplyLp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "calcOutAmountLp(uint256,(uint256,uint256),uint256,uint256)"(
      inAmount: BigNumberish,
      inTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      swapFee: BigNumberish,
      totalSupplyLp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calcOutAmountToken(
      outTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      totalSupplyLp: BigNumberish,
      inLp: BigNumberish,
      swapFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "calcOutAmountToken((uint256,uint256),uint256,uint256,uint256)"(
      outTokenReserve: { weight: BigNumberish; balance: BigNumberish },
      totalSupplyLp: BigNumberish,
      inLp: BigNumberish,
      swapFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
